version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 874ckM4m8494!
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: academease
      MYSQL_USER: rabieh
      MYSQL_PASSWORD: 874ckM4m8494!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 874ckM4m8494!
      UPLOAD_LIMIT: 10000000000

  frontend:
    image: react-app:latest
    build:
      context: ./front-gestionnaire-suivi
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: nestjs-app:latest
    build:
      context: ./back-gestionnaire-suivi
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - db

volumes:
  db_data:
